### ISSUE TITLE
Moonlight forces US Keyboard Layout

### ISSUE THREAD

**Issue by YouAreTheOneNeo** [moonlight-stream/moonlight-chrome#393]
When using moonlight to stream anything, the language bar appears on the taskbar.

This is because I am using the United Kingdom language as the default language.

Moonlight adds the US keyboard layout, causing the language bar to appear. The only way to remove it is by going into language settings and manually adding and then removing the US English Language.

Is there any way to force moonlight to use the local language of the host machine?

**Comment by Jorys-Paulin** [comment]
@YouAreTheOneNeo I use the French layout without any problems, does it changes your layout on the host or the client?

**Comment by YouAreTheOneNeo** [comment]
It changes on the host machine, client seems fine.

**Comment by Jorys-Paulin** [comment]
@YouAreTheOneNeo Maybe GeForce Experience chooses the US layout for English keyboads. Sadly we can't do anything when it comes to GeForce Experience :/

**Comment by YouAreTheOneNeo** [comment]
Interesting... I have GeForce Experience set to English (United Kingdom) so I wonder why it would pick a US keyboard!

**Comment by Jorys-Paulin** [comment]
@YouAreTheOneNeo GeForce Experience is kinda weird sometimes...

**Comment by cblavier** [comment]
I have a keyboard layout issue as well : my keyboard layout (FR - azerty) is correctly set on the windows host, but it seems that moonlight / geforce xperience is not sending correct keys, I receive qwerty keystrokes.

If I use another streaming protocol (parsec) I don't have this issue

**Comment by Jorys-Paulin** [comment]
@YouAreTheOneNeo @cblavier Are you both using GeForce Experience beta or stable?

**Comment by cblavier** [comment]
I don’t know if I’m using the beta, but I checked « Enabled experimental features »
I’m using 3.12.0.84

**Comment by Jorys-Paulin** [comment]
@cblavier I am too, I just tested and it does the same thing. Typed "azerty" on my client and got a "qwerty" input on LibreOffice. @cgutman, Any ideas?

**Comment by YouAreTheOneNeo** [comment]
FWIW I have the experimental features disabled.

**Comment by Zibbibbo** [comment]
Same problem here, on the host machine, while connected via internet the selected kayboard layout still "ITA" but it's not true, the effective layout is English US

**Comment by makedir** [comment]
I have found a workaround for it so it is working now for me.

**Comment by Jorys-Paulin** [comment]
@makedir What is it?

**Comment by makedir** [comment]
If I switch to ENG US keyboard layout on the client, it will result in the correct layout on the server. No idea why, but it does the trick. So if I switch to ENG on the client, I will have German layout on the server.

**Comment by Zebul1n** [comment]
I have the same problem with French keyboard.
as stated above it says FRA in the taskbar but it react as a ENG keyboard.

when switching to ENG as a workaround it will works for most keys but not for all of them.
also for some reason the caps are inverted meaning typing "a" on my keyboard will produce "A".

so basically i have to set the keyboard layout to ENG and activate CAPSLOCK to get most of the FRA layout to works ( enough for some games for not optimal )

**Comment by Jorys-Paulin** [comment]
@Zebul1n Les developpeurs travaillent sur une nouvelle version, j'ai reporté ce bug et il a été resolé. Malheuresement, la version chrome ne sera peut-être pas fixée :/

**Comment by Jorys-Paulin** [comment]
@makedir @Zibbibbo @YouAreTheOneNeo The devs are working on a new version which fixes this bug. The chrome version probably won't be getting a fix, as it's now deprecated.

**Comment by Zebul1n** [comment]
@Jorys-Paulin 
thanks for update ! is this new version a standalone windows client ?

**Comment by Jorys-Paulin** [comment]
@Zebul1n Yes, it is.

**Comment by Jorys-Paulin** [comment]
This is fixed in the new version, moonlight-qt ;)

**Comment by HijackHornet** [comment]
I'm still having this issue with the android client. French keyboard as well. On the server, its set to AZERTY. On the client it reacts to the QWERTY layout but not what the keyboard send. That means that if i'm using a qwerty layout on client and i click Q it will input an A. And if i use the AZERTY layout, the A becomes a Q. So no matter the layout, it decides that an A on client will always give a Q on server.
To be notted that my windows system is in english, and geforce experience as well.

**Comment by makedir** [comment]
Yes it is super annoying and still not fixed, also the parse function is useless.

**Comment by cleme29** [comment]
Hi; I have the an issue with my samsung android tablet,
If I set the following settings :

FRA on windows host, french layout keyboard and french chosen on my tablet == qwerty written but most of special characters are azerty including : the comma; dot ; semi colon ; dot 
Result : &é"'(-è_çà)=qwertyuiop^$asdfghjkl,ù*zxcvbn;m:!
Expected : &é"'(-è_çà)=**az**ertyuiop^$**q**sdfghjklmù***w**xcvbn,;:!

ENG on windows host, french layout keyboard and french chosen on my tablet == azerty written but most of special characters are qwerty including : the comma; dot ; semi colon ; dot 
Result : 1234567890-=azertyuiop[]qsdfghjklm'\wxcvbn,;./
Expected : 1234567890-=\qwertyuiop[]asdfghjkl;'zxcvbnm,./

Tell me if you need more information !
Thanks in advance !

**Comment by alagane** [comment]
Similar problem:

PC french keyboard, android french keyboard (with 3 finger tap to enable keyboard)
If I write azerty with android keyboard, it writes qwerty
Write 123 it writes &é"

If I switch to US keyboard on Windows
azerty writes azerty
123 writes 123

It seems putting the Windows keyboard layout to US fixes the  problem.

**Comment by zobi** [comment]
> Similar problem:
> 
> PC french keyboard, android french keyboard (with 3 finger tap to enable keyboard) If I write azerty with android keyboard, it writes qwerty Write 123 it writes &é"
> 
> If I switch to US keyboard on Windows azerty writes azerty 123 writes 123
> 
> It seems putting the Windows keyboard layout to US fixes the problem.

Same issue for me with pc and french keyboard and android client moonlight with french azerty keyboard too… if I configure english kb on pc and qwerty kb on android it work’s

**Comment by ghost** [comment]
Hello, I have the same problem in Brazilian Portuguese ABNT 1 and 2, I can't type question mark and other keys.

**Comment by Vaskyy** [comment]
Also still a Problem for me.
I'm using Nvidia Shield TV (2015) Version with moonlight installed on it.
The Logitech K830 (Bluetooth Connection) is set to German in Shield Settings. Moonlight is set to German locale.
My PC is set to German.
EVERZTHING is set toi German. But still when tzping on the K830 i get QWERTY... :(
Even included this in mz sunshine.conf:
```
keybindings = [
   0x5a, 0x59,
   0x59, 0x5a,
   0xbd, 0xdb,
   0xdb, 0xba,
   0xba, 0xc0,
   0xc0, 0xdc,
   0xdc, 0xbf,
   0xbf, 0xbd,
   0xdd, 0xbb,
   0xbb, 0xdd
]
```

Nothing is reallz working... as u can prollz see from mz post.. im just going with the zzz and yyy's, bc its super annozing to alwazs keep track on that.

In the sunshine log i always see that the only aceppted language is en_US:
```
[2024-09-23 08:33:39.465]: Debug: sec-ch-ua -- "Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"
[2024-09-23 08:33:39.465]: Debug: Upgrade-Insecure-Requests -- 1
[2024-09-23 08:33:39.465]: Debug: Accept-Language -- en-US,en;q=0.9,de-DE;q=0.8,de;q=0.7
[2024-09-23 08:33:39.465]: Debug: DNT -- 1
[2024-09-23 08:33:39.465]: Debug: User-Agent -- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
[2024-09-23 08:33:39.465]: Debug: Sec-Fetch-Site -- same-origin
```
